- name: This sets up an httpd webserver
  hosts: 127.0.0.1
  connection: local
  become: True
  tasks:
    - name: install php packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        loop:['php5-cli', 'php5-curl', 'php5-fpm', 'php5-intl', 'php5-json', 'php5-mcrypt', 'php5-sqlite']
  
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
