- name: This sets up an httpd webserver
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Install apache packages 
    yum:
      name: httpd
    state: latest
  - name: Restart Apache
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  - name: Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
