- name: This sets up an httpd webserver
  hosts: 127.0.0.1
  connection: local
  become: True
  tasks:
    - name: install php packages
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: latest
        update_cache: yes
  
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2
        
    - name: install mysql
      apt:
        name:
           - mariadb-client
           - mariadb-server
           - python-mysqldb
        state: latest
        update_cache: yes
g
handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
